name: Test DataStax Astra Connection

on: [push]

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Cassandra Driver
      run: npm install cassandra-driver

    - name: Test Connection to DataStax Astra
      env:
        ASTRA_SECURE_CONNECT_BUNDLE: ${{ secrets.ASTRA_SECURE_CONNECT_BUNDLE }}
        ASTRA_CLIENT_ID: ${{ secrets.ASTRA_CLIENT_ID }}
        ASTRA_CLIENT_SECRET: ${{ secrets.ASTRA_CLIENT_SECRET }}
      run: |
        echo "Testing connection to DataStax Astra..."
        node -e "
          const cassandra = require('cassandra-driver');
          const client = new cassandra.Client({
            cloud: { secureConnectBundle: process.env.ASTRA_SECURE_CONNECT_BUNDLE },
            credentials: { username: process.env.ASTRA_CLIENT_ID, password: process.env.ASTRA_CLIENT_SECRET }
          });

          async function testConnection() {
            try {
              await client.connect();
              const result = await client.execute('SELECT release_version FROM system.local');
              console.log('Connected to DataStax Astra. Release version:', result.rows[0].release_version);
            } catch (error) {
              console.error('Error connecting to DataStax Astra:', error);
              process.exit(1);
            } finally {
              await client.shutdown();
            }
          }

          testConnection();
        "
