name: Unzip File

on: [push]

jobs:
  unzip-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Unzip secure-connect-jsonmsgtest.zip
      run: unzip ./secure-connect-jsonmsgtest.zip -d ./secure-connect
